<#import "partials/main.ftlh" as main/>

<@main.renderWith>
    <section class="d-flex mx-auto">
        <div class="my-5 mx-auto d-flex justify-content-around">
            <p>This is Index!</p>
            <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
                Tooltip on top
            </button>
        </div>
    </section>
</@main.renderWith>
